---
title: "Urgent Care"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
# This document will serve as a guide on how to create charts that are changed by two crosstalk filters simultaneously. It will also serve as a guide on how to use crosstalk with flexdashboard

# This Section Sets Defaults For Rmarkdown Document
knitr::opts_chunk$set(echo = FALSE)

# This Section Loads The Necessary Packages
library(flexdashboard)
library(DT)
library(bsplus)
library(tidyverse)
library(crosstalk)
library(plotly)
library(DT)
```

```{js update-titles-from-person-filter}
// When document loads
$(document).ready(function () {
    // This part is saying only to apply changes after the flexdashboard is done loading
    $('#dashboard-container').on('flexdashboard:layoutcomplete', function () {
        // Assign onChange function to filter_select
        $('#person .selectized')[0].selectize.on('change', function () {
            var selected_value = $('#person .selectized')[0].selectize.getValue().sort(); // Get current value
            document.getElementById("bp_title").innerHTML = selected_value; // Update titles with new value
            document.getElementById("characteristics_title").innerHTML = selected_value;
        });
    });
});
```


```{r example data 1, include = FALSE}
# Create fake blood pressure readings for 5 patients: A, B, C, D, E
# These patients have been treated using 2 different medications: treatment 1 and treatment 2
# Their blood pressure has been recorded at 5 time points, with time 0 being when they took the medication

# The readings for the patients when they have taken treatment 1
BP_Readings_treatment_1 <- data.frame(
  Time = rep(seq(0, 5), 5),
  Person = rep(c("A", "B", "C", "D", "E"), each = 6),
  BP = rep(seq(10, 100, length.out = 6), 5) + rnorm(30, 0, 5)
) %>%
  mutate(Treatment = "Heart Medication 1")

# The readings for the patients when they have taken treatment 2
BP_Readings_treatment_2 <- data.frame(
  Time = rep(seq(0, 5), 5),
  Person = rep(c("A", "B", "C", "D", "E"), each = 6),
  BP = rep(seq(10, 100, length.out = 6), 5) + rnorm(30, 0, 5)
) %>%
  mutate(Treatment = "Heart Medication 2")

# Combining together to get list of all patients blood pressure readings over time for each treatment
All_BP_readings <- BP_Readings_treatment_1 %>%
  rbind(BP_Readings_treatment_2)


# We are going to be filtering our charts and table by Person and by Treatment

# Crosstalk will only take one column, which acts as a unique identifier of what information to filter for
# Since we have two different columns which uniquely identify the information we wish to keep in our charts: Person & Treatment
# we must combine the info in these two columns into one column in some way
# Most common way is shown below
All_BP_readings <- All_BP_readings %>%
  mutate(Identifier_Column = paste0(Person, "_", Treatment))

# Now our data looks like this
All_BP_readings %>%
  mutate(BP = round(BP)) %>%
  DT::datatable()
```

```{r example data 2, include = FALSE}
# We now create fake characteristics about each person

Person_Characteristics <- data.frame(
  Person = c("A", "B", "C", "D", "E"),
  Age = round(rnorm(5, 30, 10)),
  Weight = round(rnorm(5, 70, 40))
)

# We want these characteristics about each person to show up no matter what treatment is selected by our crosstalk filter
# e.g. we want our chart of characteristics about each person to be unaffected by our treatment filter

# Therefore, we must make sure that no matter what treatment is chosen, the right person information shows up
# However, the crosstalk filter will be filtering our datasets for unique identifiers that look something like those for the BP readings
# for example Patient A_Heart Medication 1

# To do this, we use the crossing function
# The crossing function will take a dataframe and a vector
# The vector represents all the unique values that a new column could take
# The crossing function will then extend the existing dataframe to have every
# combination of the columns that the dataframe already has with each of the new entries of the column created using the vector

# This function is easier to understand in practice, so here is a very simple example
example_data <- data.frame(
  Names = c("Ryan", "Eilidh", "Shahnoor"),
  Ages = c(18, 19, 20)
)

example_data <- example_data %>%
  crossing(
    Hobbies = c("Badminton", "Chess")
  )

# You can see here that the crossing function has preserved the values already present
# but added a new column which gives these values combined with the new vector values

# This is useful for us as we can create a column for treatment which will preserve the original person characteristics
# while also adding in a treatment column that we can use to create our unique identifier column

Person_Characteristics <- Person_Characteristics %>%
  crossing(Treatment = c("Heart Medication 1", "Heart Medication 2")) %>%
  mutate(Identifier_Column = paste0(Person, "_", Treatment))


# Now our data looks like
Person_Characteristics %>%
  DT::datatable()

# Now our person characteristics dataframe can be filtered by our two crosstalk filters and in essence be unaffected by the treatment filter
```


```{r lookup of people, include = FALSE}
# We now need to create a lookup of all the possible options for our two filters
# We must also include our unique identifier column in this lookup as that is what
# the crosstalk filters will be searching for in the data we are filtering

# To do this, we will use the distinct function
# this function returns all combinations of the columns provided within a dataframe
# in this instance, it is finding all unique combinations of treatments and people
# (as well as the unique identifier column, which combines the two) that are present within the data

Person_And_Treatment_Lookup <- All_BP_readings %>%
  distinct(Person, Treatment, Identifier_Column)

# this lookup looks like this

Person_And_Treatment_Lookup %>%
  DT::datatable()
```

```{r, include = FALSE}
# We now create our SharedData objects
# These are the same as our created dataframes however, they are now dynamic and
# can be affected by our crosstalk filters

# Within the creation of these SharedData objects
# We must identify the key for our data
# this is a column which uniquely identifies each entry based on our filters
# in our example, this column represents what person the data refers to and what treatment they have taken

# We must also specify a group for each data set. This refers to what filters should affect what datasets
# You would have multiple groups in the case where you have one set of filters which affect one set of charts and another set which affect another distinct set of charts
# for our example, we want our filters to affect all of our charts and tables, so we will only have one group


Person_And_Treatment_Lookup_Shared <- SharedData$new(Person_And_Treatment_Lookup, key = ~Identifier_Column, group = "BP_Group")

All_BP_readings_Shared <- SharedData$new(All_BP_readings, key = ~Identifier_Column, group = "BP_Group")

Person_Characteristics_Shared <- SharedData$new(Person_Characteristics, key = ~Identifier_Column, group = "BP_Group")
```


Row {.sidebar}
------------------------------------

```{r filter buttons}
# We now create our filters
# They take their options from their respective columns in the lookup of all options (Person_And_Treatment_Lookup)

filter_select("person", "Select Some People", Person_And_Treatment_Lookup_Shared, ~Person, multiple = TRUE)

filter_select("treatment", "Select Treatment", Person_And_Treatment_Lookup_Shared, ~Treatment, multiple = TRUE)
```


Row
------------------------------------

### BP Graph

<div style="text-align: center;">Blood Pressure For Patient <span id ="bp_title"></span></div>

```{r BP graph}
# Our Unique Identifier Column (Thing We Wish To Choose From) is the Identifier_Column Column
All_BP_readings_Shared %>%
  plot_ly(
    x = ~Time,
    y = ~BP,
    color = ~Person,
    text = ~Person,
    linetype = ~Treatment,
    hovertemplate = c("Person: %{text}\nTime: %{x}\nBP: %{y}"),
    type = "scatter",
    mode = "lines+markers"
  ) %>%
  config(
    displaylogo = FALSE,
    modeBarButtonsToRemove = c(
      "pan2d",
      "select2d",
      "lasso2d",
      "zoomIn2d",
      "zoomOut2d",
      "toggleSpikelines"
    )
  ) %>%
  layout(
    showlegend = T,
    legend = list(
      orientation = "h", # show entries horizontally
      xanchor = "center", # use center of legend as anchor
      x = 0.5,
      y = -0.2
    )
  )
```

Row
------------------------------------

### Characteristics

<div style="text-align: center;">Characteristics For Patient <span id ="characteristics_title"></span></div>

```{r characteristics graph}
Person_Characteristics_Shared %>%
  plot_ly(
    x = ~Age,
    y = ~Weight,
    color = ~Person,
    text = ~Person,
    hovertemplate = c("Person: %{text}\nAge: %{x}\nWeight: %{y}"),
    marker = list(
      size = 10,
      line = list(width = 2)
    )
  ) %>%
  config(
    displaylogo = FALSE,
    modeBarButtonsToRemove = c(
      "pan2d",
      "select2d",
      "lasso2d",
      "zoomIn2d",
      "zoomOut2d",
      "toggleSpikelines"
    )
  ) %>%
  layout(
    showlegend = T,
    legend = list(
      orientation = "h", # show entries horizontally
      xanchor = "center", # use center of legend as anchor
      x = 0.5,
      y = -0.2
    )
  )
```

``` {js initialise-dashboard-filters}
// JavaScript code using the jQuery library
// When document is ready
$(document).ready(function () {

    // This part is saying only to apply changes after the flexdashboard is done loading
    $('#dashboard-container').on('flexdashboard:layoutcomplete', function () {

        // Select Person filter and remove (all) option
        $('#person .selectized')[0].selectize.removeOption("");

        // Select Person filter and set its default value on load to Person A
        $('#person .selectized')[0].selectize.setValue("A", false);
    });

    // Called when flexdashboard content has been created. Won't work properly otherwise
    $('#dashboard-container').on('flexdashboard:layoutcomplete', function () {

        // Select Treatment filter and remove (all) option
        $('#treatment .selectized')[0].selectize.removeOption("");

        // Select Treatment filter and set its default value on load to Heart Medication 1
        $('#treatment .selectized')[0].selectize.setValue("Heart Medication 1", false);
    });
});
```
