---
title: "Urgent Care"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = FALSE)

# Load packages
library(crosstalk)
library(dplyr)
library(plotly)
```

```{js update-titles-from-person-filter}
// When document loads
$(document).ready(function () {
    // This part is saying only to apply changes after the flexdashboard is done loading
    $('#dashboard-container').on('flexdashboard:layoutcomplete', function () {
        // Assign onChange function to filter_select
        $('#person .selectized')[0].selectize.on('change', function () {
            var selected_value = $('#person .selectized')[0].selectize.getValue().sort(); // Get current value
            document.getElementById("bp_title").innerHTML = selected_value; // Update titles with new value
            document.getElementById("characteristics_title").innerHTML = selected_value;
        });
    });
});
```

```{r example data 1}
# This section creates fake blood pressure readings for 5 patients: A, B, C, D & E. We will use this data to create a chart which will be changed by a crosstalk filter.
BP_Readings <- data.frame(
  Time = rep(seq(0, 5), 5),
  Person = rep(c("A", "B", "C", "D", "E"), each = 6),
  BP = rep(seq(10, 50, length.out = 6), 5) + rnorm(30, 0, 5)
)
```

```{r example data 2}
# This section creates fake characteristics about these patients which we will use to create another chart changed by the same crosstalk filter

Person_Characteristics <- data.frame(
  Person = c("A", "B", "C", "D", "E"),
  Age = abs(round(rnorm(5, 30, 10))),
  Weight = abs(round(rnorm(5, 70, 40)))
)
```

```{r crosstalk setup}
# Our Unique Identifier Column (Thing We Wish To Choose From) is the Person Column
BP_Readings_Shared <- SharedData$new(BP_Readings, key = ~Person, group = "BP_Group")

Person_Characteristics_Shared <- SharedData$new(Person_Characteristics, key = ~Person, group = "BP_Group")
```

```{r lookup of people}
Person_Lookup <- data.frame(Person = unique(BP_Readings$Person)) %>%
  arrange(Person)

Person_Lookup_Shared <- SharedData$new(Person_Lookup, key = ~Person, group = "BP_Group")
```

```{r filter buttons}
filter_select("person", "Select Some People", Person_Lookup_Shared, ~Person, multiple = TRUE)
```

Row
------------------------------------

### BP Graph

<div style="text-align: center;">Blood Pressure For Patient <span id ="bp_title"></span></div>

```{r BP graph}
BP_Readings_Shared %>%
  plot_ly(
    x = ~Time,
    y = ~BP,
    color = ~Person,
    text = ~Person,
    hovertemplate = c("Person: %{text}\nTime: %{x}\nBP: %{y}"),
    type = "scatter",
    mode = "lines+markers"
  ) %>%
  config(
    displaylogo = FALSE,
    modeBarButtonsToRemove = c(
      "pan2d",
      "select2d",
      "lasso2d",
      "zoomIn2d",
      "zoomOut2d",
      "toggleSpikelines"
    )
  ) %>%
  layout(
    showlegend = T,
    legend = list(
      orientation = "h", # show entries horizontally
      xanchor = "center", # use center of legend as anchor
      x = 0.5,
      y = -0.2
    )
  )
```

Row
------------------------------------

### Characteristics

<div style="text-align: center;">Characteristics For Patient <span id ="characteristics_title"></span></div>

```{r characteristics graph}
Person_Characteristics_Shared %>%
  plot_ly(
    x = ~Age,
    y = ~Weight,
    color = ~Person,
    text = ~Person,
    hovertemplate = c("Person: %{text}\nAge: %{x}\nWeight: %{y}"),
    marker = list(
      size = 10,
      line = list(width = 2)
    )
  ) %>%
  config(
    displaylogo = FALSE,
    modeBarButtonsToRemove = c(
      "pan2d",
      "select2d",
      "lasso2d",
      "zoomIn2d",
      "zoomOut2d",
      "toggleSpikelines"
    )
  ) %>%
  layout(
    showlegend = T,
    legend = list(
      orientation = "h", # show entries horizontally
      xanchor = "center", # use center of legend as anchor
      x = 0.5,
      y = -0.2
    )
  )
```


``` {js initialise-person-filter}
// JavaScript code using the jQuery library
// When document is ready
$(document).ready(function () {

    // Called when flexdashboard content has been created. Won't work properly otherwise
    $('#dashboard-container').on('flexdashboard:layoutcomplete', function () {

        // Select Person filter and remove (all) option
        $('#person .selectized')[0].selectize.removeOption("");

        // Select Person filter and set its default value on load to Person A 
        $('#person .selectized')[0].selectize.setValue("A", false);
    });
});
```
