blank_issues_enabled: false
contact_links:
  - name: LIST R User Help Teams channel
    url: https://teams.microsoft.com/l/channel/19%3A9cac735aabbb46fd80dd40f1b7d3e144%40thread.tacv2/LIST%20R%20User%20Help?groupId=3e609872-2e51-443b-a14c-e1216a3636d0&tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a
    about: Please ask and answer questions here.
