name: Style the Project

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }} 
          fetch-depth: 0  # Fetch full history for accurate diff

      - name: Install air
        uses: posit-dev/setup-air@v1

      - name: Style code using air
        run: air format .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Style code"
